apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: waves-and-hooks-app
  # You'll usually want to add your resources to the argocd namespace.
  namespace: argocd
  # Add a this finalizer ONLY if you want these to cascade delete.
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # The project the application belongs to.
  project: default

  # Source of the application manifests
  source:
    repoURL: https://github.com/xi2817-aajgaonkar/argocd-practice.git
    targetRevision: HEAD
    path: waves-and-hooks

    # helm specific config
    helm:
      releaseName: my-release
  # Destination cluster and namespace to deploy the application
  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
  