apiVersion: batch/v1
kind: Job
metadata:
  generateName: integration-test1-
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-wave: "1"
spec:
  ttlSecondsAfterFinished: 10
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: ubuntu
        image: ubuntu:latest
        command: [ "sleep"]
        args: [ "{{ .Values.delay }}" ]
---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: integration-test2-
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-wave: "2"
spec:
  ttlSecondsAfterFinished: 10
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: ubuntu
        image: ubuntu:latest
        command: [ "sleep"]
        args: [ "{{ .Values.delay }}" ]